package com.kdc.wrapper;

public class PersonDemo {

    public static void main(String[] args) {

        /*
        Create a new person :
        ID : autogenerated - 001
        Firstname : ........
        Lastname : .........
        Street : ..........
        Housenumber : .....
        Floor :  .. ==> ??? What needs to be entered in the DB if it empty.

        SAVE BUTTON
         */


    }
}
